import "server-only";

import { generateText, Output } from "ai";

import { evaluationCandidateSchema } from "../domain/evaluation-schema";
import { rubricConfigs } from "../domain/rubric-config";
import type { CallType } from "../domain/types";
import { evaluatorTestModeEnabled } from "./test-mode";

export async function requestCandidate(
  prompt: string,
  repair?: string,
): Promise<unknown> {
  if (evaluatorTestModeEnabled()) return deterministicCandidate(prompt);

  const result = await generateText({
    model: "openai/gpt-5.6-luna",
    output: Output.object({ schema: evaluationCandidateSchema }),
    prompt: repair
      ? `${prompt}\n\nVALIDATION REPAIR\n${repair}\nReturn the full corrected object.`
      : prompt,
    reasoning: "high",
    maxOutputTokens: 32_000,
  });

  return result.output;
}

async function deterministicCandidate(prompt: string) {
  await new Promise((resolve) => setTimeout(resolve, 500));
  const transcript = prompt.split("\nNUMBERED TRANSCRIPT\n")[1] ?? "";
  if (transcript.includes("E2E_FORCE_FAILURE")) {
    throw new Error("Local deterministic failure");
  }

  const firstTurn = transcript.match(/^Turn 1 \| ([^:]+): (.+)$/m);
  if (!firstTurn) throw new Error("Local test transcript has no first turn");
  const callType: CallType = prompt.includes("# Coaching call")
    ? "coaching"
    : "kickoff";
  const coaching = callType === "coaching";
  const evidence = [{ turn: 1, quote: firstTurn[2] }];

  return {
    coachSpeaker: firstTurn[1],
    scoringSignals: {
      diagnosticsApplicable: {
        value: false,
        reasoning: "The local fixture does not exercise diagnostics.",
        evidence: [],
      },
      movementCoachingOccurred: {
        value: false,
        reasoning: "The local fixture does not exercise movement coaching.",
        evidence: [],
      },
      nextCallBookedLive: {
        value: false,
        reasoning: "The local fixture does not include a live booking.",
        evidence: [],
      },
    },
    oneThing: {
      improvement: "Make the next behavior explicit.",
      explanation: "A concrete next step makes the call easier to act on.",
      projectedScore: 20,
    },
    brief: "This deterministic local result verifies the complete report path.",
    redFlags: [
      {
        risk: "The next behavior is not explicit.",
        explanation: "The local fixture intentionally leaves room to improve.",
        evidence,
      },
    ],
    rawScore: 0,
    activeMaximum: 1,
    normalizedScore: 0,
    grade: "FAIL",
    dimensions: rubricConfigs[callType].dimensions.map((rule, index) => {
      const inactive = coaching && (index === 1 || index === 3);
      return {
        dimension: index + 1,
        name: `Dimension ${index + 1}`,
        score: inactive ? null : index === 0 ? (coaching ? 3 : 1) : 0,
        maximum: rule.maximum,
        active: !inactive,
        band: inactive ? "N/A" : index === 0 ? "Developing" : "Not demonstrated",
        reasoning:
          index === 0
            ? "The first speaking turn supplies deterministic local evidence."
            : "The local fixture does not demonstrate this behavior.",
        evidence: index === 0 ? evidence : [],
        missingBehavior: "The behavior was not included in the local fixture.",
        quickFix: "Demonstrate the behavior in the next call.",
      };
    }),
    appliedDimensionCaps: [],
    appliedTotalCaps: [],
    assumptions: ["This result was generated by the local E2E adapter."],
  };
}
